# Generated by Django 2.2 on 2021-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_address',
            field=models.CharField(default='Default IXN Subscriber Company', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(default='Default name', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='overview',
            field=models.CharField(default=' Default overview', max_length=5000),
        ),
    ]
