# Generated by Django 2.2 on 2021-03-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0012_acceptedprojects_rejectedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(default='', max_length=130, verbose_name='reviewer email'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='', max_length=130, verbose_name='reviewer name'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_phone_number',
            field=models.CharField(default='', max_length=130, verbose_name='reviwer phone number'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_surname',
            field=models.CharField(default='', max_length=130, verbose_name='reviewer surname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Accepeted', 'Accepted'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review'), ('Submitted', 'Submitted'), ('Paused', 'Paused')], default='', max_length=20, verbose_name='What is the current status of the project?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='CFP_Portal.Person'),
        ),
    ]
