# Generated by Django 2.2 on 2021-03-10 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0015_auto_20210310_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
