# Generated by Django 2.2 on 2021-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0019_auto_20210310_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='interoperabilityPoints100',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='researchQualityPoints100',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='resiliencePoints100',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='scalabilityPoints100',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='technical_strengthPoints100',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='usabilityTestingPoints100',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_designPoints100',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
