# Generated by Django 3.1.5 on 2021-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0021_auto_20210310_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
