# Generated by Django 3.1.5 on 2021-03-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0025_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer_phone_number',
        ),
    ]
