# Generated by Django 3.1.5 on 2021-03-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0031_remove_person_git'),
        ('CFP_Portal', '0032_auto_20210314_1516'),
    ]

    operations = [
    ]
