# Generated by Django 3.1.5 on 2021-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210310_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisation_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
