# Generated by Django 2.2 on 2021-03-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210314_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, verbose_name='git link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='linkedin link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='twitter link'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wordpress',
            field=models.URLField(blank=True, verbose_name='wordpress link'),
        ),
    ]
