# Generated by Django 3.1.5 on 2021-03-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
