# Generated by Django 2.2 on 2021-03-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210310_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, default='', verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, default='', verbose_name='git link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, default='', verbose_name='linkedin link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organisation_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True, default='', verbose_name='twitter link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wordpress',
            field=models.URLField(blank=True, default='', verbose_name='wordpress link'),
        ),
    ]
