# Generated by Django 2.2 on 2021-01-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='organisation_logo',
            field=models.ImageField(default='default_logo.png', upload_to='organisations_pics'),
        ),
    ]
