# Generated by Django 3.1.5 on 2021-01-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0004_auto_20210124_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='expertiseskills',
            field=models.TextField(default='text field', verbose_name='expertise skills'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_abstract',
            field=models.TextField(default='text field', verbose_name='text field'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='text field', max_length=130, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='person',
            name='project_title',
            field=models.CharField(default='text field', max_length=130, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='person',
            name='summarised_abstract',
            field=models.CharField(default='text field', max_length=2000, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='text field', max_length=130, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='text field', max_length=130, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='text field', max_length=130, verbose_name='surname'),
        ),
    ]
