# Generated by Django 2.2 on 2021-01-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0005_auto_20210125_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_body', models.CharField(default='', max_length=5000)),
                ('technical_quality', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('scalability', models.IntegerField()),
                ('innovation', models.IntegerField()),
                ('points', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('green', models.BooleanField()),
                ('amber', models.BooleanField()),
                ('red', models.BooleanField()),
                ('comments', models.TextField(default='', verbose_name='comments')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CFP_Portal.Person')),
            ],
        ),
    ]
