# Generated by Django 3.1.5 on 2021-01-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0005_auto_20210124_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='job_title',
        ),
        migrations.AddField(
            model_name='person',
            name='devices',
            field=models.TextField(default='', verbose_name='devices'),
        ),
        migrations.AddField(
            model_name='person',
            name='ethics_form',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='', max_length=20, verbose_name='open source or closed source'),
        ),
        
        migrations.AddField(
            model_name='person',
            name='project_complexity',
            field=models.CharField(choices=[('Scaffolding', 'Scaffolding'), ('Discovery', 'Discovery'), ('Innovation', 'Innovation')], default='', max_length=20, verbose_name='project complexity'),
        ),
        migrations.AddField(
            model_name='person',
            name='source_type',
            field=models.CharField(choices=[('Open Source', 'Open Source'), ('Closed Source', 'Closed Source')], default='', max_length=20, verbose_name='open source or closed source'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=130, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='expertiseskills',
            field=models.TextField(default='', verbose_name='expertise skills'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_abstract',
            field=models.TextField(default='', verbose_name='full abstract'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=130, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='', max_length=130, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='project_title',
            field=models.CharField(default='', max_length=130, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='summarised_abstract',
            field=models.CharField(default='', max_length=2000, verbose_name='summarised abstract'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=130, verbose_name='surname'),
        ),
    ]
