# Generated by Django 2.2 on 2021-01-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='completionPercentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('No priority', 'No priority')], default='', max_length=20, verbose_name='What is the priority level of the project?'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Waiting', 'Waiting'), ('Paused', 'Paused')], default='', max_length=20, verbose_name='What is the current status of the project?'),
        ),
    ]
