# Generated by Django 3.1.5 on 2021-01-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0006_auto_20210124_2226'),
    ]

    operations = [
        
    ]
