# Generated by Django 3.1.5 on 2021-01-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0006_auto_20210124_2226'),
    ]

    operations = [
        
    ]
