# Generated by Django 3.1.5 on 2021-02-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0007_auto_20210126_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ethics_form',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=20, verbose_name='Have you completed the ethics form?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Accepeted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Submitted', 'Submitted'), ('Paused', 'Paused')], default='', max_length=20, verbose_name='What is the current status of the project?'),
        ),
    ]
