# Generated by Django 3.1.5 on 2021-01-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0007_auto_20210124_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='launching_date',
            field=models.DateField(verbose_name='launching date'),
        ),
    ]
