# Generated by Django 3.1.5 on 2021-01-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0008_auto_20210124_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='launching_date',
        ),
    ]
