# Generated by Django 3.1.5 on 2021-01-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0009_remove_person_launching_date'),
        ('CFP_Portal', '0007_remove_person_launching_date'),
    ]

    operations = [
    ]
