# Generated by Django 3.1.5 on 2021-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0010_merge_20210124_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hashtags',
            field=models.CharField(default='hashtags', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='importance',
            field=models.TextField(default='', verbose_name='why is your project important'),
        ),
        migrations.AddField(
            model_name='person',
            name='launching_date',
            field=models.DateField(default='2021-01-25', verbose_name='launching date:'),
        ),
        migrations.AddField(
            model_name='person',
            name='motivations',
            field=models.TextField(default='', verbose_name='motivations'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ethics_form',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=20, verbose_name='Have you completed the ethics form?'),
        ),
    ]
