# Generated by Django 2.2 on 2021-03-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0010_auto_20210226_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='innovation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='scalability',
        ),
        migrations.RemoveField(
            model_name='review',
            name='technical_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='usability',
        ),
        migrations.AddField(
            model_name='review',
            name='interoperabilityComments',
            field=models.CharField(default='', max_length=2000, verbose_name='standard and interoperability'),
        ),
        migrations.AddField(
            model_name='review',
            name='interoperabilityPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='researchQualityComments',
            field=models.CharField(default='', max_length=2000, verbose_name='research quality'),
        ),
        migrations.AddField(
            model_name='review',
            name='researchQualityPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='resilienceComments',
            field=models.CharField(default='', max_length=2000, verbose_name='resilience'),
        ),
        migrations.AddField(
            model_name='review',
            name='resiliencePoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='scalabilityComments',
            field=models.CharField(default='', max_length=2000, verbose_name='scalability'),
        ),
        migrations.AddField(
            model_name='review',
            name='scalabilityPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='technical_strengthComments',
            field=models.CharField(default='', max_length=2000, verbose_name='technical strength'),
        ),
        migrations.AddField(
            model_name='review',
            name='technical_strengthPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='usabilityTestingComments',
            field=models.CharField(default='', max_length=2000, verbose_name='usability testing'),
        ),
        migrations.AddField(
            model_name='review',
            name='usabilityTestingPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='user_designComments',
            field=models.CharField(default='', max_length=2000, verbose_name='user-centred design'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_designPoints',
            field=models.IntegerField(default=0),
        ),
    ]
