# Generated by Django 3.1.5 on 2021-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0010_auto_20210226_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='', max_length=130, verbose_name='job title'),
        ),
    ]
