# Generated by Django 2.2 on 2021-03-06 19:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0011_auto_20210306_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected', to='CFP_Portal.Person')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to='CFP_Portal.Person')),
            ],
        ),
    ]
