# Generated by Django 2.2 on 2021-03-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0013_auto_20210308_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='amber',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(default='', null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='review',
            name='green',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='interoperabilityComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='standard and interoperability'),
        ),
        migrations.AlterField(
            model_name='review',
            name='interoperabilityPoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='red',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='researchQualityComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='research quality'),
        ),
        migrations.AlterField(
            model_name='review',
            name='researchQualityPoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='resilienceComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='resilience'),
        ),
        migrations.AlterField(
            model_name='review',
            name='resiliencePoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_body',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_email',
            field=models.EmailField(default='', max_length=130, null=True, verbose_name='reviewer email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='', max_length=130, null=True, verbose_name='reviewer name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_phone_number',
            field=models.CharField(default='', max_length=130, null=True, verbose_name='reviwer phone number'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_surname',
            field=models.CharField(default='', max_length=130, null=True, verbose_name='reviewer surname'),
        ),
        migrations.AlterField(
            model_name='review',
            name='scalabilityComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='scalability'),
        ),
        migrations.AlterField(
            model_name='review',
            name='scalabilityPoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='technical_strengthComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='technical strength'),
        ),
        migrations.AlterField(
            model_name='review',
            name='technical_strengthPoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='usabilityTestingComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='usability testing'),
        ),
        migrations.AlterField(
            model_name='review',
            name='usabilityTestingPoints',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_designComments',
            field=models.CharField(default='', max_length=2000, null=True, verbose_name='user-centred design'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_designPoints',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
