# Generated by Django 3.1.5 on 2021-03-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0015_auto_20210305_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='challenge',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='person',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='department'),
        ),
    ]
