# Generated by Django 2.2 on 2021-03-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0016_auto_20210310_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedprojects',
            old_name='date_accepted',
            new_name='date_rejected',
        ),
        migrations.RemoveField(
            model_name='review',
            name='points',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
    ]
