# Generated by Django 3.1.5 on 2021-03-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0016_auto_20210305_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='challenge',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organisation',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='organisation'),
        ),
    ]
