# Generated by Django 3.1.5 on 2021-03-06 13:05

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('CFP_Portal', '0017_auto_20210306_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Submitted', 'Submitted')], default='', max_length=20, verbose_name='What is the current status of the project?'),
        ),
    ]
