# Generated by Django 2.2 on 2021-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0017_auto_20210310_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
