# Generated by Django 2.2 on 2021-03-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0018_auto_20210310_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
