# Generated by Django 3.1.5 on 2021-03-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0018_auto_20210306_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='hashtags',
        ),
    ]
