# Generated by Django 3.1.5 on 2021-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0019_remove_person_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='NICEtier',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=20, verbose_name='What is the NICE tier of the project?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='challenge',
            field=models.TextField(blank=True, default='', verbose_name='Is this project from a challenge?'),
        ),
    ]
