# Generated by Django 3.1.5 on 2021-03-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0020_auto_20210309_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedprojects',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='project', serialize=False, to='CFP_Portal.person'),
        ),
    ]
