# Generated by Django 3.1.5 on 2021-03-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0022_auto_20210310_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='RAGlevel',
            field=models.CharField(default='', max_length=130, null=True, verbose_name='reviewer surname'),
        ),
    ]
