# Generated by Django 2.2 on 2021-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0023_review_raglevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='RAGlevel',
            field=models.CharField(default='', max_length=130, null=True, verbose_name='RAG level'),
        ),
    ]
