# Generated by Django 3.1.5 on 2021-03-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0026_auto_20210311_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
    ]
