# Generated by Django 2.2 on 2021-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0027_remove_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='git',
            field=models.URLField(default=''),
        ),
    ]
