# Generated by Django 3.1.5 on 2021-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0027_remove_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='evidence',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
