# Generated by Django 3.1.5 on 2021-03-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0028_person_git'),
        ('CFP_Portal', '0029_person_github'),
    ]

    operations = [
    ]
