# Generated by Django 2.2 on 2021-03-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0030_merge_20210313_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='git',
        ),
    ]
