# Generated by Django 3.1.5 on 2021-03-14 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CFP_Portal', '0031_auto_20210314_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='reviewers',
        ),
        migrations.AddField(
            model_name='person',
            name='reviewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
