# Generated by Django 2.2 on 2021-03-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0036_auto_20210318_1120'),
        ('CFP_Portal', '0036_auto_20210318_1110'),
    ]

    operations = [
    ]
