# Generated by Django 3.1.5 on 2021-03-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0037_merge_20210318_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
