# Generated by Django 3.1.5 on 2021-03-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0038_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='amber',
        ),
        migrations.RemoveField(
            model_name='review',
            name='green',
        ),
        migrations.RemoveField(
            model_name='review',
            name='red',
        ),
    ]
