# Generated by Django 3.1.5 on 2021-03-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFP_Portal', '0039_auto_20210319_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedprojects',
            old_name='date_accepted',
            new_name='date_rejected',
        ),
    ]
